apiVersion: v1
kind: PersistentVolume
metadata:
    name: artifactory-pv
    labels:
        storage: artifactory
spec:
    capacity:
        storage: 5Gi
    accessModes:
    - ReadWriteOnce
    storageClassName: normal
    hostPath:
        path: /data/k8s/artifactory
    persistentVolumeReclaimPolicy: Retain
