apiVersion: v1
kind: PersistentVolume
metadata:
    name: gitea-pv
    labels:
        storage: gitea
spec:
    capacity:
        storage: 5Gi
    accessModes:
    - ReadWriteOnce
    storageClassName: normal
    hostPath:
        path: /data/k8s/gitea
    persistentVolumeReclaimPolicy: Retain
