apiVersion: v1
kind: PersistentVolume
metadata:
    name: postgres-pv
    labels:
        storage: postgres
spec:
    capacity:
        storage: 5Gi
    accessModes:
    - ReadWriteOnce
    storageClassName: normal
    hostPath:
        path: /data/k8s/postgres
    persistentVolumeReclaimPolicy: Retain
