apiVersion: v1
kind: PersistentVolume
metadata:
    name: rabbitmq-pv
spec:
    capacity:
        storage: 5Gi
    accessModes:
    - ReadWriteOnce
    storageClassName: normal
    hostPath:
        path: /opt/k8s/rabbitmq
    persistentVolumeReclaimPolicy: Retain
