apiVersion: apps/v1
kind: Deployment
metadata:
    name: webserver-deployment
    labels:
        app: webserver
spec:
    replicas: 1
    selector:
        matchLabels:
            app: webserver
    template:
        metadata:
            labels:
                app: webserver
        spec:
            containers:
                - name: webserver-container
                  image: bazel/devops/docker/webserver:docker_webserver
                  imagePullPolicy: Never
                  volumeMounts:
                  - mountPath: /opt/certs/rootca
                    name: rootca
                    readOnly: true
                  ports:
                    - containerPort: 8080
                - name: nginx-container
                  image: bazel/devops/docker/nginx:nginx
                  imagePullPolicy: Never
                  ports:
                    - containerPort: 80
            volumes:
                - name: rootca
                  secret:
                    secretName: rootca
                    defaultMode: 256
