apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: external-webserver-service
    labels:
        app: webserver
spec:
    rules:
        - http:
            paths:
                - backend:
                    serviceName: internal-webserver-service
                    servicePort: 80
