apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: artifactory-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
    storageClassName: normal
    selector:
        matchLabels:
            storage: artifactory

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: artifactory-deployment
    labels:
        app: artifactory
spec:
    replicas: 1
    selector:
        matchLabels:
            app: artifactory
    template:
        metadata:
            labels:
                app: artifactory
        spec:
            containers:
                - name: artifactory-container
                  image: bazel/devops/docker/artifactory:artifactory
                  imagePullPolicy: Never
                  volumeMounts:
                      - name: artifactory-data
                        mountPath: /opt/jfrog/artifactory/var/data/artifactory/filestore
            volumes:
                - name: artifactory-data
                  persistentVolumeClaim:
                      claimName: artifactory-pvc
