apiVersion: v1
kind: Service
metadata:
    name: artifactory-service
    labels:
        app: artifactory
    namespace: backend
spec:
    ports:
        - port: 9998
          protocol: TCP
          name: port1
        - port: 9999
          protocol: TCP
          name: port2
    selector:
        app: artifactory
