REASSIGN OWNED BY "TEST_USER" TO postgres;
DROP OWNED BY "TEST_USER";

DROP USER IF EXISTS "TEST_USER";
CREATE USER "TEST_USER" WITH
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT
    NOREPLICATION
    NOBYPASSRLS
    ENCRYPTED PASSWORD 'asdfasdf';

GRANT SELECT ON ALL TABLES IN SCHEMA public TO "TEST_USER";
