CREATE USER "TEST_USER" WITH
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT
    NOREPLICATION
    NOBYPASSRLS
    ENCRYPTED PASSWORD 'asdfasdf';

GRANT SELECT ON ALL TABLES IN SCHEMA public TO "TEST_USER";
