apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_USER: DEVUSER
  POSTGRES_PASSWORD: password

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
    storageClassName: normal
    selector:
        matchLabels:
            storage: postgres

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgresql-deployment
    labels:
        app: postgresql
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgresql
    template:
        metadata:
            labels:
                app: postgresql
        spec:
            containers:
                - name: postgresql-container
                  image: postgres:12.2
                  imagePullPolicy: IfNotPresent
                  envFrom:
                      - configMapRef:
                          name: postgres-config
                  volumeMounts:
                      - mountPath: /var/lib/postgresql/data
                        name: postgres-data
            volumes:
                - name: postgres-data
                  persistentVolumeClaim:
                      claimName: postgres-pvc
