apiVersion: apps/v1
kind: Deployment
metadata:
    name: cloudsql-proxy-deployment
    labels:
        app: postgresql
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgresql
    template:
        metadata:
            labels:
                app: postgresql
        spec:
            containers:
                - name: cloudsql-proxy
                  image: gcr.io/cloudsql-docker/gce-proxy:1.16
                  command: ["/cloud_sql_proxy",
                             "-instances=grchive-staging:us-central1:grchive-postgresql-primary-instance=tcp:5432",
                             "-credential_file=/secrets/gke/gcloud-service-account.json"]
                  securityContext:
                      runAsUser: 2  # non-root user
                      allowPrivilegeEscalation: false
                  volumeMounts:
                      - name: gke-service-account
                        mountPath: /secrets/gke
                        readOnly: true
                  resources:
                        requests:
                            cpu: "50m"
                        limits:
                            cpu: "100m"
            volumes:
                - name: gke-service-account
                  secret:
                    secretName: gke-service-account
            imagePullSecrets:
                - name: regcred
