apiVersion: v1
kind: Service
metadata:
    name: postgresql-dev-service
    labels:
        app: postgresql
spec:
    ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432
    selector:
        app: postgresql
