apiVersion: v1
kind: Service
metadata:
    name: external-postgres-service
    labels:
        app: postgresql
spec:
    ports:
        - port: 5432
          protocol: TCP
    type: NodePort
    selector:
        app: postgresql
