apiVersion: apps/v1
kind: Deployment
metadata:
    name: vault-deployment
    labels:
        app: vault
spec:
    replicas: 1
    selector:
        matchLabels:
            app: vault
    template:
        metadata:
            labels:
                app: vault
        spec:
            containers:
                - name: vault-container
                  image: bazel/devops/docker/vault:vault
                  imagePullPolicy: Never
                  ports:
                    - containerPort: 8200
                  volumeMounts:
                      - name: internal-vault-service-certificate
                        mountPath: /opt/certs/vault
                        readOnly: true
            volumes:
                - name: internal-vault-service-certificate
                  secret:
                    secretName: internal-vault-service-certificate
                    defaultMode: 256
    strategy:
        type: Recreate
