apiVersion: v1
kind: Service
metadata:
    name: external-vault-service
    labels:
        app: vault
spec:
    ports:
        - port: 8200
          protocol: TCP
    type: NodePort
    selector:
        app: vault
