apiVersion: v1
kind: Service
metadata:
    name: internal-vault-service
    namespace: backend
    labels:
        app: vault
spec:
    ports:
        - port: 8200
          protocol: TCP
    selector:
        app: vault
