apiVersion: v1
kind: Service
metadata:
    name: gitea-service
    namespace: backend
    labels:
        app: gitea
spec:
    ports:
        - port: 3000
          protocol: TCP
    selector:
        app: gitea
