apiVersion: v1
kind: Service
metadata:
    name: external-gitea-service
    labels:
        app: gitea
spec:
    ports:
        - port: 3000
          protocol: TCP
    type: NodePort
    selector:
        app: gitea
