apiVersion: apps/v1
kind: Deployment
metadata:
    name: shell-runner-deployment
    labels:
        app: shell-runner
spec:
    replicas: 1
    selector:
        matchLabels:
            app: shell-runner
    template:
        metadata:
            labels:
                app: shell-runner
        spec:
            containers:
                - name: shell-runner-container
                  image: bazel/devops/docker/shell_runner:latest
                  imagePullPolicy: Never
