.flyway-vault:
    stage: migrate
    image: $CI_FULL_REGISTRY/ci-image:latest
    script:
        - gcloud auth activate-service-account --key-file devops/gcloud/gcloud-terraform-account.json
        - cloud_sql_proxy -instances=${GRCHIVE_PROJECT}:us-central1:${POSTGRES_INSTANCE_NAME}=tcp:5432 &
        - sleep 1
        - cd devops/database/vault
        - envsubst < flyway/prod-flyway.conf.tmpl > flyway/prod-flyway.conf
        - flyway -configFiles=./flyway/prod-flyway.conf migrate
    rules:
        - if: '$CI_COMMIT_BRANCH == "${RELEASE_BRANCH}"'
          when: never
        - changes:
            - devops/database/vault/**/*
        - when: never

.flyway-webserver:
    stage: migrate
    image: $CI_FULL_REGISTRY/ci-image:latest
    script:
        - gcloud auth activate-service-account --key-file devops/gcloud/gcloud-terraform-account.json
        - cloud_sql_proxy -instances=${GRCHIVE_PROJECT}:us-central1:${POSTGRES_INSTANCE_NAME}=tcp:5432 &
        - sleep 1
        - cd devops/database/webserver
        - envsubst < flyway/prod-flyway.conf.tmpl > flyway/prod-flyway.conf
        - flyway -configFiles=./flyway/prod-flyway.conf migrate
    rules:
        - if: '$CI_COMMIT_BRANCH == "${RELEASE_BRANCH}"'
          when: never
        - changes:
            - devops/database/webserver/**/*
        - when: never
