.terraform:
    stage: provision
    image: $CI_FULL_REGISTRY/ci-image:latest
    script:
        - cd devops/terraform/${TERRAFORM_FOLDER}
        - export TF_VAR_postgres_user=${POSTGRES_USER}
        - export TF_VAR_postgres_password=${POSTGRES_PASSWORD}
        - export TF_VAR_postgres_instance_name=${POSTGRES_INSTANCE_NAME}
        - terraform init
        - terraform apply -auto-approve
    rules:
        - if: '$CI_COMMIT_BRANCH == "${RELEASE_BRANCH}"'
          changes:
            - devops/terraform/${TERRAFORM_FOLDER}/**/*
          when: on_success
        - when: never
