apiVersion: apps/v1
kind: Deployment
metadata:
    name: rabbitmq-deployment
    labels:
        app: rabbitmq
spec:
    replicas: 1
    selector:
        matchLabels:
            app: rabbitmq
    template:
        metadata:
            labels:
                app: rabbitmq
        spec:
            containers:
            - name: rabbitmq-container
              image: bazel/devops/docker/rabbitmq:rabbitmq
              imagePullPolicy: Never
              ports:
              - containerPort: 5672
              volumeMounts:
              -  
