apiVersion: v1
kind: Service
metadata:
    name: rabbitmq-service
    namespace: backend
    labels:
        app: rabbitmq
spec:
    ports:
    - port: 5671
      protocol: TCP
    selector:
        app: rabbitmq
