apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: rabbitmq-set
    labels:
        app: rabbitmq
spec:
    selector:
        matchLabels:
            app: rabbitmq
    serviceName: "rabbitmq-service"
    replicas: 1
    template:
        metadata:
            labels:
                app: rabbitmq
        spec:
            containers:
            - name: rabbitmq-container
              image: bazel/devops/docker/rabbitmq:rabbitmq
              imagePullPolicy: Never
              ports:
              - containerPort: 5671
              volumeMounts:
              - mountPath: /var/lib/rabbitmq/mnesia
                name: rabbitmq
    volumeClaimTemplates:
      - metadata:
            name: rabbitmq
        spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "normal"
            resources:
                requests:
                    storage: 5Gi
            selector:
                matchLabels:
                    storage: rabbitmq
