self_uri = "http://localhost:8080"

[database]
connection = "user=DEVUSER dbname=audit sslmode=disable"

[login]
url = "https://dev-578359.okta.com/oauth2/default/v1"
auth_endpoint = "/authorize"
token_endpoint = "/token"
key_endpoint = "/keys"

[login.params]
client_id = "0oa1g8kug3Rsscja0357"
client_secret = "0l7rXztFrZs4AnpuYVirn5aLaDpqcdDJLBBV4GPq"
response_type = "code" 
response_mode = "query"
scope = "openid email offline_access"
redirect_uri = "/authorization-code/callback"
grant_type = "authorization_code"

[security]
session_keys = [
    "3c979da76c13832faccc7a2518e5caa211b04b5bbd69ac7a7e0a02da117f4fc6",
    "7d0c32642cf37e8fedf87e706919b9f4395b911fdf79b451b4cad74b51b946cf"
]
use_secure_cookies = false
