[database]
connection = "user=DEVUSER dbname=audit sslmode=disable"

[login]
url = "https://dev-578359.okta.com/oauth2/v1/authorize"

[login.params]
client_id = "0oa1g8kug3Rsscja0357"
response_type = "code" 
response_mode = "fragment"
scope = "openid"
redirect_uri = "http://localhost:8080/authorization-code/callback"

[security]
session_keys = [
    "3c979da76c13832faccc7a2518e5caa211b04b5bbd69ac7a7e0a02da117f4fc6",
    "7d0c32642cf37e8fedf87e706919b9f4395b911fdf79b451b4cad74b51b946cf"
]
