self_uri = "http://localhost:8080"

[company]
company_name = "Audit Stuff"
domain = "auditstuff.com"

[database]
connection = "user=DEVUSER dbname=audit sslmode=disable timezone=UTC"

[okta]
url = "https://dev-578359.okta.com"
api_key = "00RTHFmUJxvorwMdg65bHy4r9d-5aaY8a2KwVprzTo"
api_endpoint = "/api"
users_endpoint = "/v1/users"

[login]
authserver_endpoint = "/oauth2/default"
auth_endpoint = "/v1/authorize"
token_endpoint = "/v1/token"
key_endpoint = "/v1/keys"
logout_endpoint = "/v1/logout"
auth_audience = "api://default"
time_drift_leeway_seconds = 60

[login.params]
client_id = "0oa1g8kug3Rsscja0357"
client_secret = "0l7rXztFrZs4AnpuYVirn5aLaDpqcdDJLBBV4GPq"
response_type = "code" 
response_mode = "query"
scope = "openid email offline_access groups profile"
redirect_uri = "/authorization-code/callback"
grant_type = "authorization_code"

[security]
session_keys = [
    "3c979da76c13832faccc7a2518e5caa211b04b5bbd69ac7a7e0a02da117f4fc6",
    "7d0c32642cf37e8fedf87e706919b9f4395b911fdf79b451b4cad74b51b946cf"
]
use_secure_cookies = false

[vault]
url = "http://localhost:8081"
token = "s.0Elp15F398zrPUydDUtz1jez"

[backblaze]
control_doc_bucket = "bb0980597ea911e162ed011e"
keyId = "000b909e9112d1e0000000002"
key = "K000CqPXF9PgSIcGA+B8P0lvRW/6h3M"
