apiVersion: v1
kind: Service
metadata:
    name: cloudsql-service
    namespace: backend
    labels:
        app: cloudsql
spec:
    ports:
        - port: 5432
          protocol: TCP
    selector:
        app: cloudsql
