apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: script-runner-role
rules:
    - apiGroups: [""]
      resources :
          - pods
      verbs: 
        - list
        - get
        - create
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: script-runner-rolebinding
    namespace: default
subjects:
    - kind: ServiceAccount
      name: default
      namespace: default
roleRef:
    kind: ClusterRole
    name: script-runner-role
    apiGroup: rbac.authorization.k8s.io
