apiVersion: apps/v1
kind: Deployment
metadata:
    name: notification-hub-deployment
    labels:
        app: notification-hub
spec:
    replicas: 1
    selector:
        matchLabels:
            app: notification-hub
    template:
        metadata:
            labels:
                app: notification-hub
        spec:
            containers:
                - name: notification-hub-container
                  image: bazel/devops/docker/notification_hub:docker_notification_hub
                  imagePullPolicy: Never
                  volumeMounts:
                  - mountPath: /opt/certs/rootca
                    name: rootca
                    readOnly: true
            volumes:
                - name: rootca
                  secret:
                    secretName: rootca
                    defaultMode: 256

