apiVersion: apps/v1
kind: Deployment
metadata:
    name: drone-deployment
    labels:
        app: drone
spec:
    replicas: 1
    selector:
        matchLabels:
            app: drone
    template:
        metadata:
            labels:
                app: drone
        spec:
            containers:
                - name: drone-container
                  image: bazel/devops/docker/drone:drone
                  imagePullPolicy: Never
