apiVersion: v1
kind: Service
metadata:
    name: drone-service
    namespace: backend
    labels:
        app: drone
spec:
    ports:
        - port: 8888
          protocol: TCP
    selector:
        app: drone
