apiVersion: v1
kind: Service
metadata:
    name: query-runner-service
    namespace: backend
    labels:
        app: database-query-runner
spec:
    ports:
        - port: 6000
          protocol: TCP
    selector:
        app: database-query-runner
